"""Multi-language translations for Domain Tool.

Supported languages:
    vi  — Tiếng Việt (default)
    en  — English
    ja  — 日本語
    ko  — 한국어
    zh  — 中文
    de  — Deutsch
    fr  — Français
"""

LANG_NAMES = {
    'vi': 'Tiếng Việt',
    'en': 'English',
    'ja': '日本語',
    'ko': '한국어',
    'zh': '中文',
    'de': 'Deutsch',
    'fr': 'Français',
}

# English — base language (all keys defined here)
_EN = {
    # App
    'app_title':            'Domain Tool',
    # Tabs
    'tab_check':            '  Check Domain  ',
    'tab_gen':              '  Generate Domain  ',
    # Tab 1 — Checker
    'tld_filter':           'Filter by TLD — tick to select/deselect group',
    'btn_load':             'Load domains.txt',
    'btn_select_all':       'Select All',
    'btn_deselect_all':     'Deselect All',
    'lbl_threads':          'Threads:',
    'col_domain':           'Domain',
    'col_status':           'Status',
    'col_year':             'Created Year',
    'col_error':            'Error',
    'panel_title':          'Realtime Results',
    'panel_available':      'Available domains:',
    'btn_check':            'Check Domain',
    'btn_save_result':      'Save result.txt',
    # Stats
    'stat_available':       'Available: {n}',
    'stat_registered':      'Registered: {n}',
    'stat_error':           'Error: {n}',
    'stat_done':            'Done: {done} / {total}',
    'stat_speed':           'Speed: {s} /s',
    'stat_speed_init':      'Speed: — /s',
    'status_checking':      '[{done}/{total}] {domain} → {status}',
    'status_complete':      'Done!  Available: {a}   Registered: {r}   Error: {e}',
    'lbl_domain_count':     '{n} domain',
    # Context menu — Tree
    'ctx_copy_domain':      'Copy this domain',
    'ctx_copy_selected':    'Copy checked domains',
    'ctx_copy_available':   'Copy all Available',
    'ctx_sort_name':        'Sort by Name',
    'ctx_sort_year':        'Sort by Year',
    'ctx_sort_status':      'Sort by Status',
    # Context menu — Available listbox
    'avail_copy_sel':       'Copy selected domains',
    'avail_copy_all':       'Copy all',
    'avail_select_all':     'Select all',
    # Tab 2 — Generator
    'gen_name_label':       'Domain name  (enter one per line, or leave blank → random by country / topic)',
    'gen_rand_count':       'Random name count:',
    'gen_num_suffix':       'Add number suffix  (e.g. viet2347)',
    'gen_from':             '  From:',
    'gen_to':               'to:',
    'gen_num_note':         '(max 500 if range is large)',
    'gen_country':          'Country',
    'gen_topic':            'Tech Topic  (can combine multiple topics)',
    'gen_all':              'All',
    'gen_tld_label':        'TLD / Domain Extension',
    'gen_tld_entry':        'Enter TLD (priority, e.g. .com .net .vn):',
    'btn_generate':         'Generate Domain',
    'btn_save_domains':     'Save domains.txt',
    'btn_save_switch':      'Save & Switch to Check',
    'btn_copy':             'Copy',
    'gen_result':           'Result:',
    'gen_total':            'Total: {n} domain',
    # Messages
    'msg_error':            'Error',
    'msg_not_found':        'domains.txt not found',
    'msg_empty':            'Empty',
    'msg_no_results':       'No results yet',
    'msg_saved':            'Saved',
    'msg_save_ok':          'Saved to {path} successfully',
    'msg_no_domain_save':   'No domains to save',
    'msg_warning':          'Warning',
    'msg_select_check':     'Select at least 1 domain to check',
    'msg_missing':          'Missing',
    'msg_missing_name':     'Select at least 1 country / topic or enter names',
    'msg_missing_tld':      'Enter TLD or select at least 1',
    # Language
    'lbl_lang':             'Language:',
}

# Vietnamese
_VI = {
    'app_title':            'Domain Tool',
    'tab_check':            '  Check Domain  ',
    'tab_gen':              '  Tạo Domain  ',
    'tld_filter':           'Lọc theo TLD — tick để chọn/bỏ chọn cả nhóm',
    'btn_load':             'Load domains.txt',
    'btn_select_all':       'Chọn tất cả',
    'btn_deselect_all':     'Bỏ chọn tất cả',
    'lbl_threads':          'Luồng:',
    'col_domain':           'Domain',
    'col_status':           'Trạng thái',
    'col_year':             'Năm tạo',
    'col_error':            'Lỗi',
    'panel_title':          'Kết quả realtime',
    'panel_available':      'Available domains:',
    'btn_check':            'Check Domain',
    'btn_save_result':      'Lưu result.txt',
    'stat_available':       'Available: {n}',
    'stat_registered':      'Registered: {n}',
    'stat_error':           'Error: {n}',
    'stat_done':            'Done: {done} / {total}',
    'stat_speed':           'Speed: {s} /s',
    'stat_speed_init':      'Speed: — /s',
    'status_checking':      '[{done}/{total}] {domain} → {status}',
    'status_complete':      'Xong!  Available: {a}   Registered: {r}   Error: {e}',
    'lbl_domain_count':     '{n} domain',
    'ctx_copy_domain':      'Copy domain này',
    'ctx_copy_selected':    'Copy domain đã tick',
    'ctx_copy_available':   'Copy tất cả Available',
    'ctx_sort_name':        'Sắp xếp theo Tên',
    'ctx_sort_year':        'Sắp xếp theo Năm',
    'ctx_sort_status':      'Sắp xếp theo Status',
    'avail_copy_sel':       'Copy domain đã chọn',
    'avail_copy_all':       'Copy tất cả',
    'avail_select_all':     'Chọn tất cả',
    'gen_name_label':       'Tên domain  (nhập tay mỗi dòng 1 tên, hoặc để trống → random theo quốc gia / chủ đề)',
    'gen_rand_count':       'Số tên random:',
    'gen_num_suffix':       'Thêm số sau tên  (vd: viet2347)',
    'gen_from':             '  Từ:',
    'gen_to':               'đến:',
    'gen_num_note':         '(tối đa 500 nếu range lớn)',
    'gen_country':          'Quốc gia',
    'gen_topic':            'Chủ đề công nghệ  (có thể kết hợp nhiều chủ đề)',
    'gen_all':              'Tất cả',
    'gen_tld_label':        'TLD / Đuôi domain',
    'gen_tld_entry':        'Nhập TLD (ưu tiên, vd: .com .net .vn):',
    'btn_generate':         'Tạo Domain',
    'btn_save_domains':     'Lưu domains.txt',
    'btn_save_switch':      'Lưu & Chuyển sang Check',
    'btn_copy':             'Copy',
    'gen_result':           'Kết quả:',
    'gen_total':            'Tổng: {n} domain',
    'msg_error':            'Lỗi',
    'msg_not_found':        'Không tìm thấy domains.txt',
    'msg_empty':            'Trống',
    'msg_no_results':       'Chưa có kết quả',
    'msg_saved':            'Đã lưu',
    'msg_save_ok':          'Lưu vào {path} thành công',
    'msg_no_domain_save':   'Chưa có domain để lưu',
    'msg_warning':          'Cảnh báo',
    'msg_select_check':     'Chọn ít nhất 1 domain để check',
    'msg_missing':          'Thiếu',
    'msg_missing_name':     'Chọn ít nhất 1 quốc gia / chủ đề hoặc nhập tên',
    'msg_missing_tld':      'Nhập TLD hoặc chọn ít nhất 1',
    'lbl_lang':             'Ngôn ngữ:',
}

# Japanese
_JA = {
    'tab_gen':              '  ドメイン生成  ',
    'tld_filter':           'TLDフィルター — チェックでグループ選択/解除',
    'btn_select_all':       'すべて選択',
    'btn_deselect_all':     '選択解除',
    'lbl_threads':          'スレッド:',
    'col_status':           '状態',
    'col_year':             '作成年',
    'col_error':            'エラー',
    'panel_title':          'リアルタイム結果',
    'status_complete':      '完了！ Available: {a}   Registered: {r}   Error: {e}',
    'ctx_copy_domain':      'このドメインをコピー',
    'ctx_copy_selected':    'チェック済みをコピー',
    'ctx_copy_available':   '全Available をコピー',
    'ctx_sort_name':        '名前順',
    'ctx_sort_year':        '年順',
    'ctx_sort_status':      'ステータス順',
    'avail_copy_sel':       '選択をコピー',
    'avail_copy_all':       'すべてコピー',
    'avail_select_all':     'すべて選択',
    'gen_name_label':       'ドメイン名（1行ずつ入力、空白→国/トピックでランダム生成）',
    'gen_rand_count':       'ランダム数:',
    'gen_num_suffix':       '数字サフィックス追加（例: viet2347）',
    'gen_from':             '  から:',
    'gen_to':               'まで:',
    'gen_num_note':         '(範囲が大きい場合は最大500)',
    'gen_country':          '国',
    'gen_topic':            'テックトピック（複数選択可）',
    'gen_all':              'すべて',
    'gen_tld_label':        'TLD / ドメイン拡張子',
    'gen_tld_entry':        'TLDを入力（優先、例: .com .net .jp）:',
    'btn_generate':         'ドメイン生成',
    'btn_save_domains':     'domains.txt保存',
    'btn_save_switch':      '保存してCheckへ',
    'btn_copy':             'コピー',
    'gen_result':           '結果:',
    'gen_total':            '合計: {n} ドメイン',
    'msg_error':            'エラー',
    'msg_not_found':        'domains.txtが見つかりません',
    'msg_empty':            '空',
    'msg_no_results':       '結果がありません',
    'msg_saved':            '保存済み',
    'msg_save_ok':          '{path}に保存しました',
    'msg_no_domain_save':   '保存するドメインがありません',
    'msg_warning':          '警告',
    'msg_select_check':     'チェックするドメインを1つ以上選択してください',
    'msg_missing':          '不足',
    'msg_missing_name':     '国/トピックを選択するか名前を入力してください',
    'msg_missing_tld':      'TLDを入力するか1つ以上選択してください',
    'lbl_lang':             '言語:',
}

# Korean
_KO = {
    'tab_gen':              '  도메인 생성  ',
    'tld_filter':           'TLD 필터 — 체크하여 그룹 선택/해제',
    'btn_select_all':       '전체 선택',
    'btn_deselect_all':     '선택 해제',
    'lbl_threads':          '스레드:',
    'col_status':           '상태',
    'col_year':             '생성연도',
    'col_error':            '오류',
    'panel_title':          '실시간 결과',
    'status_complete':      '완료!  Available: {a}   Registered: {r}   Error: {e}',
    'ctx_copy_domain':      '이 도메인 복사',
    'ctx_copy_selected':    '체크된 도메인 복사',
    'ctx_copy_available':   '전체 Available 복사',
    'ctx_sort_name':        '이름순 정렬',
    'ctx_sort_year':        '연도순 정렬',
    'ctx_sort_status':      '상태순 정렬',
    'avail_copy_sel':       '선택 항목 복사',
    'avail_copy_all':       '전체 복사',
    'avail_select_all':     '전체 선택',
    'gen_name_label':       '도메인 이름 (한 줄에 하나씩 입력, 비워두면 → 국가/주제별 랜덤)',
    'gen_rand_count':       '랜덤 이름 수:',
    'gen_num_suffix':       '숫자 접미사 추가 (예: viet2347)',
    'gen_from':             '  부터:',
    'gen_to':               '까지:',
    'gen_num_note':         '(범위가 크면 최대 500개)',
    'gen_country':          '국가',
    'gen_topic':            '기술 주제 (복수 선택 가능)',
    'gen_all':              '전체',
    'gen_tld_label':        'TLD / 도메인 확장자',
    'gen_tld_entry':        'TLD 입력 (우선, 예: .com .net .kr):',
    'btn_generate':         '도메인 생성',
    'btn_save_domains':     'domains.txt 저장',
    'btn_save_switch':      '저장 후 Check로',
    'btn_copy':             '복사',
    'gen_result':           '결과:',
    'gen_total':            '총: {n} 도메인',
    'msg_error':            '오류',
    'msg_not_found':        'domains.txt를 찾을 수 없습니다',
    'msg_empty':            '비어있음',
    'msg_no_results':       '결과가 없습니다',
    'msg_saved':            '저장됨',
    'msg_save_ok':          '{path}에 저장되었습니다',
    'msg_no_domain_save':   '저장할 도메인이 없습니다',
    'msg_warning':          '경고',
    'msg_select_check':     '확인할 도메인을 1개 이상 선택하세요',
    'msg_missing':          '누락',
    'msg_missing_name':     '국가/주제를 선택하거나 이름을 입력하세요',
    'msg_missing_tld':      'TLD를 입력하거나 1개 이상 선택하세요',
    'lbl_lang':             '언어:',
}

# Chinese (Simplified)
_ZH = {
    'tab_gen':              '  域名生成  ',
    'tld_filter':           'TLD 筛选 — 勾选以选择/取消选择组',
    'btn_select_all':       '全选',
    'btn_deselect_all':     '取消全选',
    'lbl_threads':          '线程:',
    'col_status':           '状态',
    'col_year':             '创建年份',
    'col_error':            '错误',
    'panel_title':          '实时结果',
    'status_complete':      '完成！ Available: {a}   Registered: {r}   Error: {e}',
    'ctx_copy_domain':      '复制此域名',
    'ctx_copy_selected':    '复制已勾选域名',
    'ctx_copy_available':   '复制所有可用域名',
    'ctx_sort_name':        '按名称排序',
    'ctx_sort_year':        '按年份排序',
    'ctx_sort_status':      '按状态排序',
    'avail_copy_sel':       '复制选中项',
    'avail_copy_all':       '复制全部',
    'avail_select_all':     '全选',
    'gen_name_label':       '域名（每行输入一个，留空→按国家/主题随机生成）',
    'gen_rand_count':       '随机数量:',
    'gen_num_suffix':       '添加数字后缀（例: viet2347）',
    'gen_from':             '  从:',
    'gen_to':               '到:',
    'gen_num_note':         '(范围大时最多500个)',
    'gen_country':          '国家',
    'gen_topic':            '科技主题（可多选）',
    'gen_all':              '全部',
    'gen_tld_label':        'TLD / 域名后缀',
    'gen_tld_entry':        '输入TLD（优先，例: .com .net .cn）:',
    'btn_generate':         '生成域名',
    'btn_save_domains':     '保存 domains.txt',
    'btn_save_switch':      '保存并切换到检查',
    'btn_copy':             '复制',
    'gen_result':           '结果:',
    'gen_total':            '共: {n} 个域名',
    'msg_error':            '错误',
    'msg_not_found':        '找不到 domains.txt',
    'msg_empty':            '为空',
    'msg_no_results':       '暂无结果',
    'msg_saved':            '已保存',
    'msg_save_ok':          '已保存到 {path}',
    'msg_no_domain_save':   '没有域名可保存',
    'msg_warning':          '警告',
    'msg_select_check':     '请至少选择1个域名进行检查',
    'msg_missing':          '缺少',
    'msg_missing_name':     '请选择至少1个国家/主题或输入名称',
    'msg_missing_tld':      '请输入TLD或至少选择1个',
    'lbl_lang':             '语言:',
}

# German
_DE = {
    'tab_gen':              '  Domain generieren  ',
    'tld_filter':           'TLD-Filter — anklicken zum Auswählen/Abwählen',
    'btn_select_all':       'Alle auswählen',
    'btn_deselect_all':     'Auswahl aufheben',
    'lbl_threads':          'Threads:',
    'col_status':           'Status',
    'col_year':             'Erstellungsjahr',
    'col_error':            'Fehler',
    'panel_title':          'Echtzeit-Ergebnisse',
    'status_complete':      'Fertig!  Available: {a}   Registered: {r}   Error: {e}',
    'ctx_copy_domain':      'Domain kopieren',
    'ctx_copy_selected':    'Markierte kopieren',
    'ctx_copy_available':   'Alle verfügbaren kopieren',
    'ctx_sort_name':        'Nach Name sortieren',
    'ctx_sort_year':        'Nach Jahr sortieren',
    'ctx_sort_status':      'Nach Status sortieren',
    'avail_copy_sel':       'Auswahl kopieren',
    'avail_copy_all':       'Alle kopieren',
    'avail_select_all':     'Alle auswählen',
    'gen_name_label':       'Domain-Name (je Zeile einen eingeben, oder leer → zufällig nach Land/Thema)',
    'gen_rand_count':       'Zufällige Anzahl:',
    'gen_num_suffix':       'Zahlensuffix hinzufügen (z.B. viet2347)',
    'gen_from':             '  Von:',
    'gen_to':               'bis:',
    'gen_num_note':         '(max. 500 bei großem Bereich)',
    'gen_country':          'Land',
    'gen_topic':            'Tech-Thema (mehrere kombinierbar)',
    'gen_all':              'Alle',
    'gen_tld_label':        'TLD / Domain-Endung',
    'gen_tld_entry':        'TLD eingeben (z.B. .com .net .de):',
    'btn_generate':         'Domain generieren',
    'btn_save_domains':     'domains.txt speichern',
    'btn_save_switch':      'Speichern & zu Check',
    'btn_copy':             'Kopieren',
    'gen_result':           'Ergebnis:',
    'gen_total':            'Gesamt: {n} Domain',
    'msg_error':            'Fehler',
    'msg_not_found':        'domains.txt nicht gefunden',
    'msg_empty':            'Leer',
    'msg_no_results':       'Noch keine Ergebnisse',
    'msg_saved':            'Gespeichert',
    'msg_save_ok':          'Gespeichert in {path}',
    'msg_no_domain_save':   'Keine Domains zum Speichern',
    'msg_warning':          'Warnung',
    'msg_select_check':     'Mindestens 1 Domain zum Prüfen auswählen',
    'msg_missing':          'Fehlt',
    'msg_missing_name':     'Mindestens 1 Land/Thema wählen oder Namen eingeben',
    'msg_missing_tld':      'TLD eingeben oder mindestens 1 auswählen',
    'lbl_lang':             'Sprache:',
}

# French
_FR = {
    'tab_gen':              '  Générer domaine  ',
    'tld_filter':           'Filtrer par TLD — cocher pour sélectionner/désélectionner',
    'btn_select_all':       'Tout sélectionner',
    'btn_deselect_all':     'Tout désélectionner',
    'lbl_threads':          'Threads:',
    'col_status':           'Statut',
    'col_year':             'Année de création',
    'col_error':            'Erreur',
    'panel_title':          'Résultats en temps réel',
    'status_complete':      'Terminé !  Available: {a}   Registered: {r}   Error: {e}',
    'ctx_copy_domain':      'Copier ce domaine',
    'ctx_copy_selected':    'Copier les domaines cochés',
    'ctx_copy_available':   'Copier tous les disponibles',
    'ctx_sort_name':        'Trier par nom',
    'ctx_sort_year':        'Trier par année',
    'ctx_sort_status':      'Trier par statut',
    'avail_copy_sel':       'Copier la sélection',
    'avail_copy_all':       'Tout copier',
    'avail_select_all':     'Tout sélectionner',
    'gen_name_label':       'Nom de domaine (un par ligne, ou vide → aléatoire par pays/sujet)',
    'gen_rand_count':       'Nombre aléatoire:',
    'gen_num_suffix':       'Ajouter suffixe numérique (ex: viet2347)',
    'gen_from':             '  De:',
    'gen_to':               'à:',
    'gen_num_note':         '(max 500 si la plage est grande)',
    'gen_country':          'Pays',
    'gen_topic':            'Sujet tech (combinaison possible)',
    'gen_all':              'Tous',
    'gen_tld_label':        'TLD / Extension de domaine',
    'gen_tld_entry':        'Entrer TLD (priorité, ex: .com .net .fr):',
    'btn_generate':         'Générer domaine',
    'btn_save_domains':     'Sauver domains.txt',
    'btn_save_switch':      'Sauver & aller à Check',
    'btn_copy':             'Copier',
    'gen_result':           'Résultat:',
    'gen_total':            'Total: {n} domaine',
    'msg_error':            'Erreur',
    'msg_not_found':        'domains.txt introuvable',
    'msg_empty':            'Vide',
    'msg_no_results':       'Pas encore de résultats',
    'msg_saved':            'Sauvegardé',
    'msg_save_ok':          'Sauvegardé dans {path}',
    'msg_no_domain_save':   'Aucun domaine à sauvegarder',
    'msg_warning':          'Attention',
    'msg_select_check':     'Sélectionnez au moins 1 domaine à vérifier',
    'msg_missing':          'Manquant',
    'msg_missing_name':     'Sélectionnez au moins 1 pays/sujet ou entrez des noms',
    'msg_missing_tld':      'Entrez un TLD ou sélectionnez-en au moins 1',
    'lbl_lang':             'Langue:',
}

# Merged dict — each lang falls back to English for missing keys
LANGUAGES = {
    'en': _EN,
    'vi': {**_EN, **_VI},
    'ja': {**_EN, **_JA},
    'ko': {**_EN, **_KO},
    'zh': {**_EN, **_ZH},
    'de': {**_EN, **_DE},
    'fr': {**_EN, **_FR},
}
